# Build stage with musl target
FROM rust:1.88-alpine AS base


# Add openssl-libs-static for static linking
RUN apk add --no-cache musl-dev openssl-dev openssl-libs-static pkgconfig
RUN cargo install --locked cargo-chef sccache

FROM base AS planner
WORKDIR /app
# Copy the Cargo.toml and Cargo.lock files
COPY Cargo.toml Cargo.lock ./
# Copy the rest of the source code
COPY src ./src

RUN cargo chef prepare --recipe-path recipe.json

FROM base AS builder
WORKDIR /app
COPY --from=planner /app/recipe.json recipe.json
# Build dependencies
RUN cargo chef cook --release --recipe-path recipe.json --bin producer

COPY Cargo.toml Cargo.lock ./
COPY src ./src
RUN cargo build --release --bin consumer

# Alpine runtime - much smaller!
FROM alpine:3.22 AS runtime
# RUN apk add --no-cache ca-certificates libgcc libssl3 curl bash

# # Install Fluvio CLI
# RUN curl -fsS https://hub.infinyon.cloud/install/install.sh?ctx=dc | bash
# ENV PATH="/root/.fluvio/bin:$PATH"

COPY --from=builder /app/target/release/consumer /usr/local/bin/consumer

# # Create startup script
# RUN printf '#!/bin/sh\n\
#     echo "Waiting for Fluvio cluster..."\n\
#     sleep 10\n\
#     echo "Adding Fluvio profile..."\n\
#     fluvio profile add docker sc:9003 docker || true\n\
#     echo "Starting producer..."\n\
#     exec producer\n' > /start.sh && chmod +x /start.sh

# CMD ["/start.sh"]

CMD ["consumer"]