# Build stage with musl target
FROM rust:alpine AS base


# Add openssl-libs-static for static linking
RUN apk add --no-cache musl-dev openssl-dev openssl-libs-static pkgconfig
RUN cargo install --locked cargo-chef sccache

FROM base AS planner
WORKDIR /app
# Copy the Cargo.toml and Cargo.lock files
COPY Cargo.toml Cargo.lock ./
# Copy the rest of the source code
COPY src ./src


RUN cargo chef prepare --recipe-path recipe.json

FROM base AS builder
WORKDIR /app
COPY --from=planner /app/recipe.json recipe.json
# Build dependencies
RUN cargo chef cook --release --recipe-path recipe.json --bin producer

COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY .sqlx ./.sqlx
COPY migrations ./migrations
RUN cargo build --release --bin producer

FROM alpine:3.22 AS runtime
# RUN apk add --no-cache ca-certificates libgcc libssl3 curl bash

COPY --from=builder /app/target/release/producer /usr/local/bin/producer
COPY configuration configuration
ENV MARKET_ENVIRONMENT=production

WORKDIR /

CMD ["producer"]