services:
  iggy:
    #image: apache/iggy:edge
    image: iggyrs/iggy:latest
    container_name: iggy
    restart: unless-stopped
    environment:
      - IGGY_ROOT_USERNAME=iggy
      - IGGY_ROOT_PASSWORD=Secret123!
      - IGGY_HTTP_ENABLED=true
      - IGGY_HTTP_ADDRESS=0.0.0.0:80
      - IGGY_TCP_ENABLED=true
      - IGGY_TCP_ADDRESS=0.0.0.0:3000
      - IGGY_QUIC_ENABLED=false
      - IGGY_HEARTBEAT_ENABLED=true
      - IGGY_HEARTBEAT_INTERVAL=5s
    ports:
      - "3010:80"
      - "5100:3000"
    networks:
      - iggy-network
    volumes:
      - iggy:/iggy/local_data
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3000 || exit 1"]
      start_period: 5s
      interval: 1s
      timeout: 1s
      retries: 2


  iggy-web-ui:
    image: iggyrs/iggy-web-ui:latest
    container_name: iggy-web-ui
    restart: unless-stopped
    environment:
      - PUBLIC_IGGY_API_URL=http://iggy:80
    ports:
      - "3050:3050"
    networks:
      - iggy-network
    depends_on:
      - iggy



  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    networks:
      - timescale-network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=market_data
    volumes:
      - timescale-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d market_data"]
      interval: 10s
      timeout: 5s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    networks:
      - timescale-network
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - POSTGRES_HOST=timescaledb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=market_data
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - 5050:80
    depends_on:
      timescaledb:
        condition: service_healthy
    user: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    # entrypoint: |
    #   #!/bin/sh
    #   SERVERS_JSON_PATH="/pgadmin4/servers.json"
    #   PGPASSFILE="$HOME/.pgpass"

    #   # Create the .pgpass file for password
    #   echo "Creating pgpass file at $PGPASSFILE"
    #   echo "${POSTGRES_HOST}:*:*:${POSTGRES_USER}:${POSTGRES_PASSWORD}" > "$PGPASSFILE"
    #   chmod 600 $PGPASSFILE
    #   cat $PGPASSFILE
    #   echo "pgpass file created successfully."

    #   echo "Creating servers.json file in $SERVERS_JSON_PATH"
    #   cat << EOF > $SERVERS_JSON_PATH
    #   {
    #       "Servers": {
    #           "1": {
    #               "Name": "My Postgres",
    #               "Group": "Servers",
    #               "Host": "${POSTGRES_HOST}",
    #               "Port": ${POSTGRES_PORT},
    #               "MaintenanceDB": "${POSTGRES_DB}",
    #               "Username": "${POSTGRES_USER}",
    #               "PassFile": "$PGPASSFILE",
    #               "SSLMode": "prefer"
    #           }
    #       }
    #   }
    #   EOF

    #   echo "$SERVERS_JSON_PATH file created successfully."
    #   cat $SERVERS_JSON_PATH

    #   echo "Starting pgAdmin4..."
    #   exec /entrypoint.sh
    #   echo "pgAdmin4 started."


  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    networks:
      - iggy-network
      - timescale-network
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana



  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    container_name: market-making-producer
    networks:
      - iggy-network
      - timescale-network
    depends_on:
      timescaledb:
        condition: service_healthy

    environment:
      - RUST_LOG=warn
      - SYMBOLS=BTCUSDT,ETHUSDT,BNBUSDT,SOLUSDT,DOTUSDT,DOGEUSDT,MAGICUSDT,ETHBTC
    restart: unless-stopped

networks:
  iggy-network:
  timescale-network:

volumes:
  iggy:
  timescale-data:
  pgadmin-data:
  grafana-storage: